[workspace]
resolver = "3"
members = ["crates/*", "examples/echo"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
gramhive-core = { path = "crates/gramhive-core" }
gramhive-macros = { path = "crates/gramhive-macros" }
gramhive-grammers = { path = "crates/gramhive-grammers" }
gramhive-test = { path = "crates/gramhive-test" }
gramhive = { path = "crates/gramhive", default-features = false }
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }
tokio = { version = "1", features = ["sync"] }
thiserror = "2"
tracing = "0.1"
