[package]
name = "gramhive_macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "gramhive_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
deluxe = "0.5.0"
